### ISSUE TITLE
Environment setup for new users

### ISSUE THREAD

**Issue by alexanderzjs** [wklchris/Note-by-LaTeX#9]
Chris, thanks for your guide on how to use latex. However, lots of new users may struggle on installing the texlive or any other environments. It might be helpful if your guide could include a chapter for new users to get started with those tools on differnet platforms.

From my point of view, new users may be confused at various compilation options such as latex, pdflatex, pdftex, xetex, xelatex and how to find proper packages to support their functionality.

If this issue is not proper, feel free to close it.

**Comment by wklchris** [comment]
Hi Alexander, thank you for your suggestions. This handbook uses the TeX Live distribution (or its macOS version MacTeX; I think there's few difference), the TeXstudio editor and the XeLaTeX compiler, so I won't mention other distributions like MikTeX. And I've covered following things in the book:
- The TeX Live installation is kind of straightforward and there are also many instructions on the Internet. Another option is the published version of this book. The editor from the publisher requested me for an additional chapter for installation. 
- Though I didn't include figures, I verbally introduced the configuration of TeXstudio with XeLaTeX in the book (see Chapter 3.1, the latest version is [v1.6.4-pre](https://github.com/wklchris/Note-by-LaTeX/releases/v1.6.4)).

If you have TeX Live on your machine, you don't need external packages for different compilers because these compilers go with the TeX Live installation. I choose XeLaTeX since it provides satisfactory Chinese support. However, you can select any compiler from the dropdown list in the TeXstudio settings. It actually replace `xelatex` to other compiler (and may also change some arguments) in the compilation chain command.
